Repository planetscale/vitess-operator, pull requests merged in 2024-10, with the labels that each got.

#610 Support customisation of docker images per-keyspace
  deploy/crds/planetscale.com_vitessclusters.yaml
  docs/api/index.html
  pkg/apis/planetscale/v2/vitesskeyspace_defaults.go
  pkg/apis/planetscale/v2/vitesskeyspace_types.go
  test/endtoend/operator/operator-latest.yaml
Labels: enhancement, Backport to: release-2.13, Backport to: release-2.14, Backport to: release-2.12, Backport to: release-2.11

#618 Update README for 2.14 release
  README.md
Labels: Backport to: release-2.14

#612 Update `docs/api.md` and automatically update it
  Makefile
  docs/api.md
  docs/api/index.html
  docs/api/template/pkg.tpl
Labels: Backport to: release-2.14

#620 [release-2.14] Update docs/api.md and automatically update it
  Makefile
  docs/api.md
  docs/api/index.html
  docs/api/template/members.tpl
  docs/api/template/pkg.tpl
  docs/api/template/type.tpl
Labels: Backport
